<?php
// Mikhmon Notification Settings (Sprint 3)
// For lightnet19 fork only.

error_reporting(0);

if (!isset($_SESSION["mikhmon"])) {
  header("Location:../admin.php?id=login");
  exit;
}

// Load configurations
include_once './include/config.php';

// notif_config.php di-generate otomatis saat admin simpan pengaturan.
// Jika belum ada (fresh install), gunakan nilai default yang aman.
if (file_exists('./include/notif_config.php')) {
    include_once './include/notif_config.php';
} else {
    $notif_config = [
        'telegram_enabled' => false,
        'telegram_token'   => '',
        'telegram_chat_id' => '',
        'wa_enabled'       => false,
        'wa_gateway_url'   => 'http://127.0.0.1:3001',
        'wa_gateway_key'   => '',
        'wa_targets'       => '',
        'cpu_threshold'    => 80.0,
        'memory_threshold' => 85.0,
        'router_thresholds' => [],
    ];
}

include_once './lib/telegram_notif.php';
include_once './lib/wa_notif.php';


$message_info = '';

// Handle POST actions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_verify();
    
    if (isset($_POST['save_notif'])) {
        $telegram_enabled = isset($_POST['telegram_enabled']) && $_POST['telegram_enabled'] === '1';
        $telegram_token = trim($_POST['telegram_token']);
        $telegram_chat_id = trim($_POST['telegram_chat_id']);
        
        $wa_enabled = isset($_POST['wa_enabled']) && $_POST['wa_enabled'] === '1';
        $wa_gateway_url = trim($_POST['wa_gateway_url']);
        $wa_gateway_key = trim($_POST['wa_gateway_key']);
        $wa_targets = trim($_POST['wa_targets']);
        
        $cpu_threshold = (float)($_POST['cpu_threshold'] ?? 80.0);
        $memory_threshold = (float)($_POST['memory_threshold'] ?? 85.0);
        
        // Router thresholds override
        $router_thresholds = [];
        if (isset($_POST['router_cpu']) && is_array($_POST['router_cpu'])) {
            foreach ($_POST['router_cpu'] as $r_ses => $r_cpu) {
                $r_mem = $_POST['router_mem'][$r_ses] ?? 85.0;
                $router_thresholds[$r_ses] = [
                    'cpu' => (float)$r_cpu,
                    'mem' => (float)$r_mem
                ];
            }
        }
        
        // Save to include/notif_config.php
        $new_config = [
            'telegram_enabled' => $telegram_enabled,
            'telegram_token'   => $telegram_token,
            'telegram_chat_id' => $telegram_chat_id,
            'wa_enabled'       => $wa_enabled,
            'wa_gateway_url'   => $wa_gateway_url,
            'wa_gateway_key'   => $wa_gateway_key,
            'wa_targets'       => $wa_targets,
            'cpu_threshold'    => $cpu_threshold,
            'memory_threshold' => $memory_threshold,
            'router_thresholds' => $router_thresholds,
        ];
        
        $export = var_export($new_config, true);
        $content = "<?php\n// Mikhmon Notification Configuration\n// Generated by: settings/notif_settings.php\n\n\$notif_config = {$export};\n";
        
        if (file_put_contents('./include/notif_config.php', $content)) {
            $notif_config = $new_config; // Update local reference
            $message_info = '<div class="alert alert-success"><i class="fa fa-check"></i> Configuration saved successfully!</div>';
        } else {
            $message_info = '<div class="alert alert-danger"><i class="fa fa-times"></i> Failed to write config file. Check permissions!</div>';
        }
    }
}

// Handle AJAX actions
if (isset($_GET['ajax'])) {
    header('Content-Type: application/json');
    
    if ($_GET['ajax'] === 'wa_status') {
        $status = check_wa_gateway_status();
        echo json_encode($status);
        exit;
    }
    
    if ($_GET['ajax'] === 'test_tg') {
        $msg = "🔔 *Mikhmon Test Notification*\nTelegram notification integration is working properly!";
        $res = send_telegram_notification($msg);
        echo json_encode(['success' => $res]);
        exit;
    }
    
    if ($_GET['ajax'] === 'test_wa') {
        $phone = $_GET['phone'] ?? '';
        if ($phone === '') {
            $targets = explode(',', $notif_config['wa_targets'] ?? '');
            $phone = trim($targets[0] ?? '');
        }
        if ($phone === '') {
            echo json_encode(['success' => false, 'error' => 'No target phone number set.']);
            exit;
        }
        $msg = "🔔 *Mikhmon Test Notification*\nWhatsApp Baileys gateway integration is working properly!";
        $res = send_wa_notification($phone, $msg);
        echo json_encode(['success' => $res]);
        exit;
    }
}

?>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3><i class="fa fa-bell"></i> Notification Settings &nbsp; | &nbsp;&nbsp;<i onclick="location.reload();" class="fa fa-refresh pointer" title="Reload data"></i></h3>
            </div>
            <div class="card-body">
                <?= $message_info; ?>
                
                <form autocomplete="off" method="post" action="./admin.php?id=notif" name="notif_settings">
                    <?= csrf_field(); ?>
                    
                    <div class="row">
                        <!-- Left Column: Settings -->
                        <div class="col-6">
                            
                            <!-- Telegram Alert Card -->
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fa fa-paper-plane"></i> Telegram Alerts</h3>
                                </div>
                                <div class="card-body">
                                    <table class="table table-sm">
                                        <tr>
                                            <td class="align-middle" style="width: 150px;">Enabled</td>
                                            <td>
                                                <select class="form-control" name="telegram_enabled">
                                                    <option value="0" <?= !($notif_config['telegram_enabled'] ?? false) ? 'selected' : ''; ?>>Disabled</option>
                                                    <option value="1" <?= ($notif_config['telegram_enabled'] ?? false) ? 'selected' : ''; ?>>Enabled</option>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle">Bot Token</td>
                                            <td>
                                                <input class="form-control" type="text" name="telegram_token" value="<?= htmlspecialchars($notif_config['telegram_token'] ?? ''); ?>" placeholder="123456789:ABCdefGhIjk..." />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle">Chat ID</td>
                                            <td>
                                                <input class="form-control" type="text" name="telegram_chat_id" value="<?= htmlspecialchars($notif_config['telegram_chat_id'] ?? ''); ?>" placeholder="-100123456789" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td>
                                                <button type="button" id="btnTestTg" class="btn btn-sm btn-info" style="cursor: pointer;"><i class="fa fa-paper-plane-o"></i> Test Telegram</button>
                                                <span id="testTgStatus" style="margin-left: 10px; font-weight: bold;"></span>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            
                            <!-- WhatsApp Baileys Card -->
                            <div class="card" style="margin-top: 15px;">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fa fa-whatsapp"></i> WhatsApp (Baileys Multi-Device)</h3>
                                </div>
                                <div class="card-body">
                                    <table class="table table-sm">
                                        <tr>
                                            <td class="align-middle" style="width: 150px;">Enabled</td>
                                            <td>
                                                <select class="form-control" name="wa_enabled">
                                                    <option value="0" <?= !($notif_config['wa_enabled'] ?? false) ? 'selected' : ''; ?>>Disabled</option>
                                                    <option value="1" <?= ($notif_config['wa_enabled'] ?? false) ? 'selected' : ''; ?>>Enabled</option>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle">Gateway URL</td>
                                            <td>
                                                <input class="form-control" type="text" name="wa_gateway_url" value="<?= htmlspecialchars($notif_config['wa_gateway_url'] ?? 'http://127.0.0.1:3001'); ?>" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle">Gateway API Key</td>
                                            <td>
                                                <input class="form-control" type="password" id="wa_gateway_key" name="wa_gateway_key" value="<?= htmlspecialchars($notif_config['wa_gateway_key'] ?? ''); ?>" />
                                                <small style="display:block;margin-top:2px;"><input type="checkbox" onclick="var x=document.getElementById('wa_gateway_key');x.type=x.type==='password'?'text':'password';"> Show Key</small>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle">Target Numbers</td>
                                            <td>
                                                <input class="form-control" type="text" name="wa_targets" value="<?= htmlspecialchars($notif_config['wa_targets'] ?? ''); ?>" placeholder="62812345678,62898765432" />
                                                <small class="text-muted">Comma-separated numbers starting with country code (e.g. 628...)</small>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td>
                                                <button type="button" id="btnTestWa" class="btn btn-sm btn-info" style="cursor: pointer;"><i class="fa fa-paper-plane-o"></i> Test WhatsApp</button>
                                                <span id="testWaStatus" style="margin-left: 10px; font-weight: bold;"></span>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            
                            <!-- Global Thresholds Card -->
                            <div class="card" style="margin-top: 15px;">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fa fa-dashboard"></i> Global Alert Thresholds</h3>
                                </div>
                                <div class="card-body">
                                    <table class="table table-sm">
                                        <tr>
                                            <td class="align-middle" style="width: 150px;">CPU Usage (%)</td>
                                            <td>
                                                <input class="form-control" type="number" step="0.1" name="cpu_threshold" value="<?= (float)($notif_config['cpu_threshold'] ?? 80.0); ?>" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle">Memory Usage (%)</td>
                                            <td>
                                                <input class="form-control" type="number" step="0.1" name="memory_threshold" value="<?= (float)($notif_config['memory_threshold'] ?? 85.0); ?>" required />
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                        
                        <!-- Right Column: Status & Overrides -->
                        <div class="col-6">
                            
                            <!-- WA Gateway Connection Status Card -->
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fa fa-info-circle"></i> Gateway Status</h3>
                                </div>
                                <div class="card-body text-center" id="gatewayStatusContainer">
                                    <div style="font-size: 16px; margin-bottom: 10px;">
                                        Gateway Service: <span id="gw_service_badge" class="badge bg-danger">Checking...</span>
                                        &nbsp;&nbsp;
                                        WhatsApp: <span id="gw_conn_badge" class="badge bg-danger">Checking...</span>
                                    </div>
                                    
                                    <!-- QR Code Area -->
                                    <div id="qr_container" style="display: none; border: 1px solid var(--border-color); padding: 15px; background: white; margin: 10px auto; max-width: 280px; border-radius: 5px;">
                                        <h4 style="margin: 0 0 10px 0; color: #333;">Scan to Connect</h4>
                                        <div id="qr_image_wrapper"></div>
                                        <p style="margin: 10px 0 0 0; font-size: 12px; color: #666;">Open WhatsApp > Linked Devices > Link a Device.</p>
                                    </div>
                                    
                                    <div id="gw_info_details" class="text-muted" style="margin-top: 10px; font-size: 13px;">
                                        Gateway URL: <code id="gw_url_val">-</code>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- WA Gateway Anti-Ban Status Card -->
                            <div class="card" style="margin-top: 15px;">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fa fa-shield"></i> Anti-Ban Protection Dashboard</h3>
                                </div>
                                <div class="card-body">
                                    <table class="table table-sm" style="margin-bottom: 0;">
                                        <tr>
                                            <td style="width: 150px;">Queue Length</td>
                                            <td><span id="ab_queue" class="badge bg-info">0</span></td>
                                        </tr>
                                        <tr>
                                            <td>Daily Limit</td>
                                            <td><span id="ab_daily_count">0</span> / <span id="ab_daily_limit">0</span></td>
                                        </tr>
                                        <tr>
                                            <td>Hourly Limit</td>
                                            <td><span id="ab_hourly_count">0</span> / <span id="ab_hourly_limit">0</span></td>
                                        </tr>
                                        <tr>
                                            <td>Warm-up Mode</td>
                                            <td><span id="ab_warmup" class="badge bg-secondary">Disabled</span></td>
                                        </tr>
                                        <tr id="ab_pause_row" style="display: none;">
                                            <td colspan="2">
                                                <div class="alert alert-danger" style="margin: 5px 0 0 0; padding: 5px 10px; font-size: 12px;">
                                                    <i class="fa fa-warning"></i> Gateway is temporarily PAUSED due to consecutive failures.
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            
                            <!-- Router Overrides Card -->
                            <div class="card" style="margin-top: 15px;">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fa fa-server"></i> Router-Specific Thresholds</h3>
                                </div>
                                <div class="card-body" style="padding: 0;">
                                    <table class="table table-bordered table-hover" style="margin-bottom: 0;">
                                        <thead>
                                            <tr>
                                                <th>Router / Session</th>
                                                <th>CPU Alert Threshold (%)</th>
                                                <th>Memory Alert Threshold (%)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $has_routers = false;
                                            foreach ($data as $ses_name => $ses_arr) {
                                                if ($ses_name === "" || $ses_name === "mikhmon") continue;
                                                $has_routers = true;
                                                
                                                // Get current override values or default to global
                                                $curr_cpu = $notif_config['router_thresholds'][$ses_name]['cpu'] ?? $notif_config['cpu_threshold'] ?? 80.0;
                                                $curr_mem = $notif_config['router_thresholds'][$ses_name]['mem'] ?? $notif_config['memory_threshold'] ?? 85.0;
                                                
                                                echo "<tr>
                                                    <td class='align-middle'><strong>{$ses_name}</strong></td>
                                                    <td><input class='form-control form-control-sm' type='number' step='0.1' name='router_cpu[{$ses_name}]' value='{$curr_cpu}' required /></td>
                                                    <td><input class='form-control form-control-sm' type='number' step='0.1' name='router_mem[{$ses_name}]' value='{$curr_mem}' required /></td>
                                                </tr>";
                                            }
                                            
                                            if (!$has_routers) {
                                                echo "<tr><td colspan='3' class='text-center text-muted'>No routers configured. Create a router session first.</td></tr>";
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                    <!-- Action Bar -->
                    <div class="row" style="margin-top: 20px;">
                        <div class="col-12 text-right">
                            <button type="submit" name="save_notif" class="btn btn-primary" style="cursor: pointer;"><i class="fa fa-save"></i> Save Notification Settings</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
.badge {
    display: inline-block;
    padding: .25em .4em;
    font-size: 75%;
    font-weight: 700;
    line-height: 1;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: .25rem;
    color: #fff;
}
.bg-success { background-color: #28a745; }
.bg-danger { background-color: #dc3545; }
.bg-warning { background-color: #ffc107; color: #111; }
.alert {
    padding: .75rem 1.25rem;
    margin-bottom: 1rem;
    border: 1px solid transparent;
    border-radius: .25rem;
}
.alert-success {
    color: #155724;
    background-color: #d4edda;
    border-color: #c3e6cb;
}
.alert-danger {
    color: #721c24;
    background-color: #f8d7da;
    border-color: #f5c6cb;
}
</style>

<script>
$(document).ready(function() {
    // Sync URL in details
    $('#gw_url_val').text($('input[name="wa_gateway_url"]').val());
    
    // Status polling
    function pollGatewayStatus() {
        var url = $('input[name="wa_gateway_url"]').val();
        $('#gw_url_val').text(url);
        
        $.ajax({
            url: './admin.php?id=notif&ajax=wa_status',
            dataType: 'json',
            timeout: 3000,
            success: function(data) {
                if (data.online) {
                    $('#gw_service_badge').removeClass('bg-danger bg-warning').addClass('bg-success').text('ONLINE');
                    
                    if (data.connected) {
                        $('#gw_conn_badge').removeClass('bg-danger bg-warning').addClass('bg-success').text('CONNECTED (' + data.user + ')');
                        $('#qr_container').hide();
                    } else if (data.status === 'qrcode' && data.qr) {
                        $('#gw_conn_badge').removeClass('bg-danger bg-success').addClass('bg-warning').text('AWAITING SCAN');
                        // Render QR Code using api.qrserver.com
                        var qrImgUrl = 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&margin=0&data=' + encodeURIComponent(data.qr);
                        $('#qr_image_wrapper').html('<img src="' + qrImgUrl + '" alt="WhatsApp QR Code" style="display:block;margin:0 auto;" />');
                        $('#qr_container').show();
                    } else {
                        $('#gw_conn_badge').removeClass('bg-success bg-warning').addClass('bg-danger').text('DISCONNECTED');
                        $('#qr_container').hide();
                    }
                    
                    // Update Anti-Ban Dashboard
                    if (data.antiBan) {
                        $('#ab_queue').text(data.antiBan.queueLength);
                        $('#ab_daily_count').text(data.antiBan.dailyCount);
                        $('#ab_daily_limit').text(data.antiBan.dailyLimit);
                        $('#ab_hourly_count').text(data.antiBan.hourlyCount);
                        $('#ab_hourly_limit').text(data.antiBan.hourlyLimit);
                        
                        if (data.antiBan.warmupMode) {
                            $('#ab_warmup').removeClass('bg-secondary').addClass('bg-warning').text('ACTIVE (Day ' + data.antiBan.warmupDays + ')');
                        } else {
                            $('#ab_warmup').removeClass('bg-warning').addClass('bg-secondary').text('Disabled');
                        }
                        
                        if (data.antiBan.isPaused) {
                            $('#ab_pause_row').show();
                        } else {
                            $('#ab_pause_row').hide();
                        }
                    }
                } else {
                    $('#gw_service_badge').removeClass('bg-success bg-warning').addClass('bg-danger').text('OFFLINE');
                    $('#gw_conn_badge').removeClass('bg-success bg-warning').addClass('bg-danger').text('OFFLINE');
                    $('#qr_container').hide();
                    
                    // Reset Anti-Ban Dashboard
                    $('#ab_queue').text('-');
                    $('#ab_daily_count').text('-');
                    $('#ab_daily_limit').text('-');
                    $('#ab_hourly_count').text('-');
                    $('#ab_hourly_limit').text('-');
                    $('#ab_warmup').removeClass('bg-warning').addClass('bg-secondary').text('OFFLINE');
                    $('#ab_pause_row').hide();
                }
            },
            error: function() {
                $('#gw_service_badge').removeClass('bg-success bg-warning').addClass('bg-danger').text('OFFLINE');
                $('#gw_conn_badge').removeClass('bg-success bg-warning').addClass('bg-danger').text('OFFLINE');
                $('#qr_container').hide();
                
                // Reset Anti-Ban Dashboard
                $('#ab_queue').text('-');
                $('#ab_daily_count').text('-');
                $('#ab_daily_limit').text('-');
                $('#ab_hourly_count').text('-');
                $('#ab_hourly_limit').text('-');
                $('#ab_warmup').removeClass('bg-warning').addClass('bg-secondary').text('OFFLINE');
                $('#ab_pause_row').hide();
            }
        });
    }
    
    // Poll immediately and every 5 seconds
    pollGatewayStatus();
    setInterval(pollGatewayStatus, 5000);
    
    // Test Telegram Bot
    $('#btnTestTg').click(function() {
        $('#testTgStatus').text('Sending...').css('color', '#888');
        $.ajax({
            url: './admin.php?id=notif&ajax=test_tg',
            dataType: 'json',
            success: function(data) {
                if (data.success) {
                    $('#testTgStatus').text('Test sent successfully!').css('color', '#28a745');
                } else {
                    $('#testTgStatus').text('Failed to send test. Check token/chat_id.').css('color', '#dc3545');
                }
            },
            error: function() {
                $('#testTgStatus').text('Connection error.').css('color', '#dc3545');
            }
        });
    });
    
    // Test WhatsApp
    $('#btnTestWa').click(function() {
        var targets = $('input[name="wa_targets"]').val().split(',');
        var phone = targets[0] ? targets[0].trim() : '';
        if (phone === '') {
            $('#testWaStatus').text('Set a target number first!').css('color', '#dc3545');
            return;
        }
        
        $('#testWaStatus').text('Sending...').css('color', '#888');
        $.ajax({
            url: './admin.php?id=notif&ajax=test_wa&phone=' + encodeURIComponent(phone),
            dataType: 'json',
            success: function(data) {
                if (data.success) {
                    $('#testWaStatus').text('Test sent to ' + phone + '!').css('color', '#28a745');
                } else {
                    $('#testWaStatus').text('Failed to send test. Gateway offline or unconnected.').css('color', '#dc3545');
                }
            },
            error: function() {
                $('#testWaStatus').text('Connection error.').css('color', '#dc3545');
            }
        });
    });
});
</script>
